<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TaskSeeder extends Seeder
{
    public function run(): void
    {
        $tasks = [
            [
                'task_title' => 'Implement User Authentication',
                'task_description' => 'Create login and registration system with JWT',
                'task_client_id' => 1,
                'task_project_id' => 1,
                'task_system_id' => 1,
                'task_category_id' => 1,
                'task_priority_id' => 2,
                'task_status_id' => 2,
                'task_type_id' => 1,
                'task_assign_to' => 4,
                'task_user_id' => 2,
                'task_due_date' => Carbon::now()->addDays(7),
                'task_date_start' => Carbon::now(),
                'task_date_end' => Carbon::now()->addDays(7),
                'task_time_start' => '09:00:00',
                'task_time_end' => '17:00:00',
                'task_remarks' => 'Use Laravel Sanctum',
            ],
            [
                'task_title' => 'Fix Payment Gateway Bug',
                'task_description' => 'Investigate and fix payment processing error',
                'task_client_id' => 2,
                'task_project_id' => 2,
                'task_system_id' => 5,
                'task_category_id' => 2,
                'task_priority_id' => 1,
                'task_status_id' => 1,
                'task_type_id' => 3,
                'task_assign_to' => 4,
                'task_user_id' => 2,
                'task_due_date' => Carbon::now()->addDays(2),
                'task_date_start' => Carbon::now(),
                'task_date_end' => Carbon::now()->addDays(2),
                'task_time_start' => '10:00:00',
                'task_time_end' => '18:00:00',
                'task_remarks' => 'Urgent fix needed',
            ],
            [
                'task_title' => 'Design Database Schema',
                'task_description' => 'Create ERD and database structure for new module',
                'task_client_id' => 3,
                'task_project_id' => 3,
                'task_system_id' => 3,
                'task_category_id' => 4,
                'task_priority_id' => 3,
                'task_status_id' => 3,
                'task_type_id' => 2,
                'task_assign_to' => 5,
                'task_user_id' => 3,
                'task_due_date' => Carbon::now()->addDays(5),
                'task_date_start' => Carbon::now(),
                'task_date_end' => Carbon::now()->addDays(5),
                'task_time_start' => '09:00:00',
                'task_time_end' => '17:00:00',
                'task_remarks' => 'Include all relationships',
            ],
            [
                'task_title' => 'Write Unit Tests',
                'task_description' => 'Create comprehensive test coverage for API endpoints',
                'task_client_id' => 4,
                'task_project_id' => 4,
                'task_system_id' => 2,
                'task_category_id' => 3,
                'task_priority_id' => 4,
                'task_status_id' => 1,
                'task_type_id' => 4,
                'task_assign_to' => 7,
                'task_user_id' => 4,
                'task_due_date' => Carbon::now()->addDays(10),
                'task_date_start' => Carbon::now(),
                'task_date_end' => Carbon::now()->addDays(10),
                'task_time_start' => '11:00:00',
                'task_time_end' => '19:00:00',
                'task_remarks' => 'Focus on edge cases',
            ],
            [
                'task_title' => 'Create User Documentation',
                'task_description' => 'Write user manual for new features',
                'task_client_id' => 5,
                'task_project_id' => 5,
                'task_system_id' => 4,
                'task_category_id' => 4,
                'task_priority_id' => 5,
                'task_status_id' => 4,
                'task_type_id' => 4,
                'task_assign_to' => 3,
                'task_user_id' => 5,
                'task_due_date' => Carbon::now()->addDays(15),
                'task_date_start' => Carbon::now(),
                'task_date_end' => Carbon::now()->addDays(15),
                'task_time_start' => '08:00:00',
                'task_time_end' => '16:00:00',
                'task_remarks' => 'Include screenshots',
            ],
            [
                'task_title' => 'Performance Optimization',
                'task_description' => 'Optimize database queries and caching',
                'task_client_id' => 6,
                'task_project_id' => 6,
                'task_system_id' => 7,
                'task_category_id' => 7,
                'task_priority_id' => 2,
                'task_status_id' => 2,
                'task_type_id' => 2,
                'task_assign_to' => 4,
                'task_user_id' => 6,
                'task_due_date' => Carbon::now()->addDays(20),
                'task_date_start' => Carbon::now(),
                'task_date_end' => Carbon::now()->addDays(20),
                'task_time_start' => '13:00:00',
                'task_time_end' => '21:00:00',
                'task_remarks' => 'Focus on slow queries',
            ],
            [
                'task_title' => 'Security Audit',
                'task_description' => 'Perform security review and penetration testing',
                'task_client_id' => 7,
                'task_project_id' => 7,
                'task_system_id' => 6,
                'task_category_id' => 6,
                'task_priority_id' => 1,
                'task_status_id' => 1,
                'task_type_id' => 6,
                'task_assign_to' => 6,
                'task_user_id' => 7,
                'task_due_date' => Carbon::now()->addDays(3),
                'task_date_start' => Carbon::now(),
                'task_date_end' => Carbon::now()->addDays(3),
                'task_time_start' => '09:00:00',
                'task_time_end' => '17:00:00',
                'task_remarks' => 'High priority security check',
            ],
        ];

        foreach ($tasks as $task) {
            DB::table('tasks')->insert(array_merge($task, [
                'task_log_datetime' => Carbon::now()->subDays(rand(0, 15)),
                'task_inactive' => 0,
                'task_edit_pending' => 0,
                'task_pending_data' => null,
            ]));
        }
    }
}